import { OrbitControls } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import Image from 'next/image'
import { Suspense } from 'react'
import { Parallax } from 'react-scroll-parallax'
import About from '../components/About'
import Animated from '../components/Animated'
import Contact from '../components/Contact'
import Intro from '../components/Intro'
import Nav from '../components/Nav'
import Sphere_shape from '../components/Sphere_shape'
import Strengths from '../components/Strengths'
import Technologies from '../components/Technologies'


export default function Home() {
  return (
    <div className={`  bg-[#277bc0] px-5 md:px-20 max-w-screen-2xl mx-auto  w-full space-y-40`} >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@700&display=swap" rel="stylesheet"/>
      </Head>
    
      
      <main className='typ  flex 
      space-y-10 flex-col  h-full'>
      <div className='h-screen  lg:space-y-40 '>
          <Nav />
          <div className='md:grid relative   sm:flex  sm:flex-col items-center md:grid-flow-row md:grid-cols-12'>
          <div className='space-y-5 h-96 px-5 md:px-10 col-span-7'>
            <span className='absolute right-0'>
              <div className='bg-[#fff4cf] w-0.5 h-96 flex flex-col justify-between '>
                <div className='w-6 h-0.5  md:bg-[#fff4cf] bg-[#277bc0] ' />
                <div className='w-6 h-0.5 bg-[#fff4cf] ' />
              </div>
            </span>
            <span className='absolute bottom-0'>
              <div className='bg-[#fff4cf] w-96 h-0.5 flex flex-col justify-between '>
                
              </div>
            </span>
          
            <div className=' md:hidden h-96   col-span-5'>
        
              <Canvas className=' absolute'>
                <OrbitControls enableZoom={false}/>
                <ambientLight intensity={0.5} />
                <directionalLight position={[-2, 5, 2]} intensity={1}/>
                <Suspense>
                  <Animated />
                </Suspense>
                
              </Canvas>
            </div>
            <Intro />
        </div>

        <div className='hidden md:inline h-96 col-span-5'>
        
          <Canvas className=''>
            <OrbitControls enableZoom={false}/>
            <ambientLight intensity={0.5} />
            <directionalLight position={[-2, 5, 2]} intensity={1}/>
            <Suspense>
              <Animated />
            </Suspense>
            
          </Canvas>
        </div>
        </div>
      </div>
        
      
      {/*About Me */}
        
        <div>
          <About />
        </div>

        {/*Stengths */}
        <div>
          <div className='sm:px-5'>
            <p></p>
            <Strengths />
          </div>
        </div>
        {/*Technologies */}
        <div>
          <div className='sm:px-5 pt-10'>
            <Technologies />
          </div>
        </div>
        {/*Technologies */}
        <div>
          <div className='sm:px-5 pt-10'>
            <Contact />
          </div>
        </div>
      </main>

      
    </div>
  )
}
